// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tsrob/l7portal-go/models"
)

// CreateOrganizationReader is a Reader for the CreateOrganization structure.
type CreateOrganizationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateOrganizationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateOrganizationCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateOrganizationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateOrganizationNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateOrganizationInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateOrganizationCreated creates a CreateOrganizationCreated with default headers values
func NewCreateOrganizationCreated() *CreateOrganizationCreated {
	return &CreateOrganizationCreated{}
}

/*
CreateOrganizationCreated describes a response with status code 201, with default header values.

An object describing a single newly created Organization.
*/
type CreateOrganizationCreated struct {
	Payload *models.Organization
}

// IsSuccess returns true when this create organization created response has a 2xx status code
func (o *CreateOrganizationCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create organization created response has a 3xx status code
func (o *CreateOrganizationCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create organization created response has a 4xx status code
func (o *CreateOrganizationCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create organization created response has a 5xx status code
func (o *CreateOrganizationCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create organization created response a status code equal to that given
func (o *CreateOrganizationCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the create organization created response
func (o *CreateOrganizationCreated) Code() int {
	return 201
}

func (o *CreateOrganizationCreated) Error() string {
	return fmt.Sprintf("[POST /Organizations][%d] createOrganizationCreated  %+v", 201, o.Payload)
}

func (o *CreateOrganizationCreated) String() string {
	return fmt.Sprintf("[POST /Organizations][%d] createOrganizationCreated  %+v", 201, o.Payload)
}

func (o *CreateOrganizationCreated) GetPayload() *models.Organization {
	return o.Payload
}

func (o *CreateOrganizationCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Organization)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateOrganizationBadRequest creates a CreateOrganizationBadRequest with default headers values
func NewCreateOrganizationBadRequest() *CreateOrganizationBadRequest {
	return &CreateOrganizationBadRequest{}
}

/*
CreateOrganizationBadRequest describes a response with status code 400, with default header values.

Bad Request due to a validation error.
*/
type CreateOrganizationBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this create organization bad request response has a 2xx status code
func (o *CreateOrganizationBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create organization bad request response has a 3xx status code
func (o *CreateOrganizationBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create organization bad request response has a 4xx status code
func (o *CreateOrganizationBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create organization bad request response has a 5xx status code
func (o *CreateOrganizationBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create organization bad request response a status code equal to that given
func (o *CreateOrganizationBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create organization bad request response
func (o *CreateOrganizationBadRequest) Code() int {
	return 400
}

func (o *CreateOrganizationBadRequest) Error() string {
	return fmt.Sprintf("[POST /Organizations][%d] createOrganizationBadRequest  %+v", 400, o.Payload)
}

func (o *CreateOrganizationBadRequest) String() string {
	return fmt.Sprintf("[POST /Organizations][%d] createOrganizationBadRequest  %+v", 400, o.Payload)
}

func (o *CreateOrganizationBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateOrganizationBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateOrganizationNotFound creates a CreateOrganizationNotFound with default headers values
func NewCreateOrganizationNotFound() *CreateOrganizationNotFound {
	return &CreateOrganizationNotFound{}
}

/*
CreateOrganizationNotFound describes a response with status code 404, with default header values.

Entity not found
*/
type CreateOrganizationNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this create organization not found response has a 2xx status code
func (o *CreateOrganizationNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create organization not found response has a 3xx status code
func (o *CreateOrganizationNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create organization not found response has a 4xx status code
func (o *CreateOrganizationNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this create organization not found response has a 5xx status code
func (o *CreateOrganizationNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this create organization not found response a status code equal to that given
func (o *CreateOrganizationNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the create organization not found response
func (o *CreateOrganizationNotFound) Code() int {
	return 404
}

func (o *CreateOrganizationNotFound) Error() string {
	return fmt.Sprintf("[POST /Organizations][%d] createOrganizationNotFound  %+v", 404, o.Payload)
}

func (o *CreateOrganizationNotFound) String() string {
	return fmt.Sprintf("[POST /Organizations][%d] createOrganizationNotFound  %+v", 404, o.Payload)
}

func (o *CreateOrganizationNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateOrganizationNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateOrganizationInternalServerError creates a CreateOrganizationInternalServerError with default headers values
func NewCreateOrganizationInternalServerError() *CreateOrganizationInternalServerError {
	return &CreateOrganizationInternalServerError{}
}

/*
CreateOrganizationInternalServerError describes a response with status code 500, with default header values.

Internal Server Error. Certain fields are missing from the request.
*/
type CreateOrganizationInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this create organization internal server error response has a 2xx status code
func (o *CreateOrganizationInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create organization internal server error response has a 3xx status code
func (o *CreateOrganizationInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create organization internal server error response has a 4xx status code
func (o *CreateOrganizationInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create organization internal server error response has a 5xx status code
func (o *CreateOrganizationInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create organization internal server error response a status code equal to that given
func (o *CreateOrganizationInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create organization internal server error response
func (o *CreateOrganizationInternalServerError) Code() int {
	return 500
}

func (o *CreateOrganizationInternalServerError) Error() string {
	return fmt.Sprintf("[POST /Organizations][%d] createOrganizationInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateOrganizationInternalServerError) String() string {
	return fmt.Sprintf("[POST /Organizations][%d] createOrganizationInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateOrganizationInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateOrganizationInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
