// Code generated by go-swagger; DO NOT EDIT.

package applications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/tsrob/l7portal-go/models"
)

// NewCreateAPIKeyUsingPOSTParams creates a new CreateAPIKeyUsingPOSTParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateAPIKeyUsingPOSTParams() *CreateAPIKeyUsingPOSTParams {
	return &CreateAPIKeyUsingPOSTParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateAPIKeyUsingPOSTParamsWithTimeout creates a new CreateAPIKeyUsingPOSTParams object
// with the ability to set a timeout on a request.
func NewCreateAPIKeyUsingPOSTParamsWithTimeout(timeout time.Duration) *CreateAPIKeyUsingPOSTParams {
	return &CreateAPIKeyUsingPOSTParams{
		timeout: timeout,
	}
}

// NewCreateAPIKeyUsingPOSTParamsWithContext creates a new CreateAPIKeyUsingPOSTParams object
// with the ability to set a context for a request.
func NewCreateAPIKeyUsingPOSTParamsWithContext(ctx context.Context) *CreateAPIKeyUsingPOSTParams {
	return &CreateAPIKeyUsingPOSTParams{
		Context: ctx,
	}
}

// NewCreateAPIKeyUsingPOSTParamsWithHTTPClient creates a new CreateAPIKeyUsingPOSTParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateAPIKeyUsingPOSTParamsWithHTTPClient(client *http.Client) *CreateAPIKeyUsingPOSTParams {
	return &CreateAPIKeyUsingPOSTParams{
		HTTPClient: client,
	}
}

/*
CreateAPIKeyUsingPOSTParams contains all the parameters to send to the API endpoint

	for the create Api key using p o s t operation.

	Typically these are written to a http.Request.
*/
type CreateAPIKeyUsingPOSTParams struct {

	/* APIKeyDto.

	   The API key to create.
	*/
	APIKeyDto *models.APIKeyDto

	/* AppUUID.

	   The Application UUID to create the API key for.
	*/
	AppUUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create Api key using p o s t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateAPIKeyUsingPOSTParams) WithDefaults() *CreateAPIKeyUsingPOSTParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create Api key using p o s t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateAPIKeyUsingPOSTParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create Api key using p o s t params
func (o *CreateAPIKeyUsingPOSTParams) WithTimeout(timeout time.Duration) *CreateAPIKeyUsingPOSTParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create Api key using p o s t params
func (o *CreateAPIKeyUsingPOSTParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create Api key using p o s t params
func (o *CreateAPIKeyUsingPOSTParams) WithContext(ctx context.Context) *CreateAPIKeyUsingPOSTParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create Api key using p o s t params
func (o *CreateAPIKeyUsingPOSTParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create Api key using p o s t params
func (o *CreateAPIKeyUsingPOSTParams) WithHTTPClient(client *http.Client) *CreateAPIKeyUsingPOSTParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create Api key using p o s t params
func (o *CreateAPIKeyUsingPOSTParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIKeyDto adds the aPIKeyDto to the create Api key using p o s t params
func (o *CreateAPIKeyUsingPOSTParams) WithAPIKeyDto(aPIKeyDto *models.APIKeyDto) *CreateAPIKeyUsingPOSTParams {
	o.SetAPIKeyDto(aPIKeyDto)
	return o
}

// SetAPIKeyDto adds the apiKeyDto to the create Api key using p o s t params
func (o *CreateAPIKeyUsingPOSTParams) SetAPIKeyDto(aPIKeyDto *models.APIKeyDto) {
	o.APIKeyDto = aPIKeyDto
}

// WithAppUUID adds the appUUID to the create Api key using p o s t params
func (o *CreateAPIKeyUsingPOSTParams) WithAppUUID(appUUID string) *CreateAPIKeyUsingPOSTParams {
	o.SetAppUUID(appUUID)
	return o
}

// SetAppUUID adds the appUuid to the create Api key using p o s t params
func (o *CreateAPIKeyUsingPOSTParams) SetAppUUID(appUUID string) {
	o.AppUUID = appUUID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateAPIKeyUsingPOSTParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.APIKeyDto != nil {
		if err := r.SetBodyParam(o.APIKeyDto); err != nil {
			return err
		}
	}

	// path param appUuid
	if err := r.SetPathParam("appUuid", o.AppUUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
