// Code generated by go-swagger; DO NOT EDIT.

package applications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tsrob/l7portal-go/models"
)

// GetApplicationAPIGroupUsingUUIDReader is a Reader for the GetApplicationAPIGroupUsingUUID structure.
type GetApplicationAPIGroupUsingUUIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetApplicationAPIGroupUsingUUIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetApplicationAPIGroupUsingUUIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetApplicationAPIGroupUsingUUIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetApplicationAPIGroupUsingUUIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetApplicationAPIGroupUsingUUIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetApplicationAPIGroupUsingUUIDOK creates a GetApplicationAPIGroupUsingUUIDOK with default headers values
func NewGetApplicationAPIGroupUsingUUIDOK() *GetApplicationAPIGroupUsingUUIDOK {
	return &GetApplicationAPIGroupUsingUUIDOK{}
}

/*
GetApplicationAPIGroupUsingUUIDOK describes a response with status code 200, with default header values.

OK
*/
type GetApplicationAPIGroupUsingUUIDOK struct {
	Payload []*models.ApplicationAPIGroupReference
}

// IsSuccess returns true when this get application Api group using Uuid o k response has a 2xx status code
func (o *GetApplicationAPIGroupUsingUUIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get application Api group using Uuid o k response has a 3xx status code
func (o *GetApplicationAPIGroupUsingUUIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get application Api group using Uuid o k response has a 4xx status code
func (o *GetApplicationAPIGroupUsingUUIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get application Api group using Uuid o k response has a 5xx status code
func (o *GetApplicationAPIGroupUsingUUIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get application Api group using Uuid o k response a status code equal to that given
func (o *GetApplicationAPIGroupUsingUUIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get application Api group using Uuid o k response
func (o *GetApplicationAPIGroupUsingUUIDOK) Code() int {
	return 200
}

func (o *GetApplicationAPIGroupUsingUUIDOK) Error() string {
	return fmt.Sprintf("[GET /api-management/1.0/applications/{appUuid}/api-groups][%d] getApplicationApiGroupUsingUuidOK  %+v", 200, o.Payload)
}

func (o *GetApplicationAPIGroupUsingUUIDOK) String() string {
	return fmt.Sprintf("[GET /api-management/1.0/applications/{appUuid}/api-groups][%d] getApplicationApiGroupUsingUuidOK  %+v", 200, o.Payload)
}

func (o *GetApplicationAPIGroupUsingUUIDOK) GetPayload() []*models.ApplicationAPIGroupReference {
	return o.Payload
}

func (o *GetApplicationAPIGroupUsingUUIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApplicationAPIGroupUsingUUIDBadRequest creates a GetApplicationAPIGroupUsingUUIDBadRequest with default headers values
func NewGetApplicationAPIGroupUsingUUIDBadRequest() *GetApplicationAPIGroupUsingUUIDBadRequest {
	return &GetApplicationAPIGroupUsingUUIDBadRequest{}
}

/*
GetApplicationAPIGroupUsingUUIDBadRequest describes a response with status code 400, with default header values.

Bad Request due to a validation error.
*/
type GetApplicationAPIGroupUsingUUIDBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this get application Api group using Uuid bad request response has a 2xx status code
func (o *GetApplicationAPIGroupUsingUUIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get application Api group using Uuid bad request response has a 3xx status code
func (o *GetApplicationAPIGroupUsingUUIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get application Api group using Uuid bad request response has a 4xx status code
func (o *GetApplicationAPIGroupUsingUUIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get application Api group using Uuid bad request response has a 5xx status code
func (o *GetApplicationAPIGroupUsingUUIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get application Api group using Uuid bad request response a status code equal to that given
func (o *GetApplicationAPIGroupUsingUUIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get application Api group using Uuid bad request response
func (o *GetApplicationAPIGroupUsingUUIDBadRequest) Code() int {
	return 400
}

func (o *GetApplicationAPIGroupUsingUUIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /api-management/1.0/applications/{appUuid}/api-groups][%d] getApplicationApiGroupUsingUuidBadRequest  %+v", 400, o.Payload)
}

func (o *GetApplicationAPIGroupUsingUUIDBadRequest) String() string {
	return fmt.Sprintf("[GET /api-management/1.0/applications/{appUuid}/api-groups][%d] getApplicationApiGroupUsingUuidBadRequest  %+v", 400, o.Payload)
}

func (o *GetApplicationAPIGroupUsingUUIDBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetApplicationAPIGroupUsingUUIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApplicationAPIGroupUsingUUIDNotFound creates a GetApplicationAPIGroupUsingUUIDNotFound with default headers values
func NewGetApplicationAPIGroupUsingUUIDNotFound() *GetApplicationAPIGroupUsingUUIDNotFound {
	return &GetApplicationAPIGroupUsingUUIDNotFound{}
}

/*
GetApplicationAPIGroupUsingUUIDNotFound describes a response with status code 404, with default header values.

Entity not found
*/
type GetApplicationAPIGroupUsingUUIDNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this get application Api group using Uuid not found response has a 2xx status code
func (o *GetApplicationAPIGroupUsingUUIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get application Api group using Uuid not found response has a 3xx status code
func (o *GetApplicationAPIGroupUsingUUIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get application Api group using Uuid not found response has a 4xx status code
func (o *GetApplicationAPIGroupUsingUUIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get application Api group using Uuid not found response has a 5xx status code
func (o *GetApplicationAPIGroupUsingUUIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get application Api group using Uuid not found response a status code equal to that given
func (o *GetApplicationAPIGroupUsingUUIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get application Api group using Uuid not found response
func (o *GetApplicationAPIGroupUsingUUIDNotFound) Code() int {
	return 404
}

func (o *GetApplicationAPIGroupUsingUUIDNotFound) Error() string {
	return fmt.Sprintf("[GET /api-management/1.0/applications/{appUuid}/api-groups][%d] getApplicationApiGroupUsingUuidNotFound  %+v", 404, o.Payload)
}

func (o *GetApplicationAPIGroupUsingUUIDNotFound) String() string {
	return fmt.Sprintf("[GET /api-management/1.0/applications/{appUuid}/api-groups][%d] getApplicationApiGroupUsingUuidNotFound  %+v", 404, o.Payload)
}

func (o *GetApplicationAPIGroupUsingUUIDNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetApplicationAPIGroupUsingUUIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApplicationAPIGroupUsingUUIDInternalServerError creates a GetApplicationAPIGroupUsingUUIDInternalServerError with default headers values
func NewGetApplicationAPIGroupUsingUUIDInternalServerError() *GetApplicationAPIGroupUsingUUIDInternalServerError {
	return &GetApplicationAPIGroupUsingUUIDInternalServerError{}
}

/*
GetApplicationAPIGroupUsingUUIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error. Certain fields are missing from the request.
*/
type GetApplicationAPIGroupUsingUUIDInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this get application Api group using Uuid internal server error response has a 2xx status code
func (o *GetApplicationAPIGroupUsingUUIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get application Api group using Uuid internal server error response has a 3xx status code
func (o *GetApplicationAPIGroupUsingUUIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get application Api group using Uuid internal server error response has a 4xx status code
func (o *GetApplicationAPIGroupUsingUUIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get application Api group using Uuid internal server error response has a 5xx status code
func (o *GetApplicationAPIGroupUsingUUIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get application Api group using Uuid internal server error response a status code equal to that given
func (o *GetApplicationAPIGroupUsingUUIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get application Api group using Uuid internal server error response
func (o *GetApplicationAPIGroupUsingUUIDInternalServerError) Code() int {
	return 500
}

func (o *GetApplicationAPIGroupUsingUUIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api-management/1.0/applications/{appUuid}/api-groups][%d] getApplicationApiGroupUsingUuidInternalServerError  %+v", 500, o.Payload)
}

func (o *GetApplicationAPIGroupUsingUUIDInternalServerError) String() string {
	return fmt.Sprintf("[GET /api-management/1.0/applications/{appUuid}/api-groups][%d] getApplicationApiGroupUsingUuidInternalServerError  %+v", 500, o.Payload)
}

func (o *GetApplicationAPIGroupUsingUUIDInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetApplicationAPIGroupUsingUUIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
