// Code generated by go-swagger; DO NOT EDIT.

package applications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPublishApplicationUsingUUIDParams creates a new PublishApplicationUsingUUIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPublishApplicationUsingUUIDParams() *PublishApplicationUsingUUIDParams {
	return &PublishApplicationUsingUUIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPublishApplicationUsingUUIDParamsWithTimeout creates a new PublishApplicationUsingUUIDParams object
// with the ability to set a timeout on a request.
func NewPublishApplicationUsingUUIDParamsWithTimeout(timeout time.Duration) *PublishApplicationUsingUUIDParams {
	return &PublishApplicationUsingUUIDParams{
		timeout: timeout,
	}
}

// NewPublishApplicationUsingUUIDParamsWithContext creates a new PublishApplicationUsingUUIDParams object
// with the ability to set a context for a request.
func NewPublishApplicationUsingUUIDParamsWithContext(ctx context.Context) *PublishApplicationUsingUUIDParams {
	return &PublishApplicationUsingUUIDParams{
		Context: ctx,
	}
}

// NewPublishApplicationUsingUUIDParamsWithHTTPClient creates a new PublishApplicationUsingUUIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPublishApplicationUsingUUIDParamsWithHTTPClient(client *http.Client) *PublishApplicationUsingUUIDParams {
	return &PublishApplicationUsingUUIDParams{
		HTTPClient: client,
	}
}

/*
PublishApplicationUsingUUIDParams contains all the parameters to send to the API endpoint

	for the publish application using Uuid operation.

	Typically these are written to a http.Request.
*/
type PublishApplicationUsingUUIDParams struct {

	/* AppUUID.

	   UUID of the Application to be publish.
	*/
	AppUUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the publish application using Uuid params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PublishApplicationUsingUUIDParams) WithDefaults() *PublishApplicationUsingUUIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the publish application using Uuid params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PublishApplicationUsingUUIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the publish application using Uuid params
func (o *PublishApplicationUsingUUIDParams) WithTimeout(timeout time.Duration) *PublishApplicationUsingUUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the publish application using Uuid params
func (o *PublishApplicationUsingUUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the publish application using Uuid params
func (o *PublishApplicationUsingUUIDParams) WithContext(ctx context.Context) *PublishApplicationUsingUUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the publish application using Uuid params
func (o *PublishApplicationUsingUUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the publish application using Uuid params
func (o *PublishApplicationUsingUUIDParams) WithHTTPClient(client *http.Client) *PublishApplicationUsingUUIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the publish application using Uuid params
func (o *PublishApplicationUsingUUIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppUUID adds the appUUID to the publish application using Uuid params
func (o *PublishApplicationUsingUUIDParams) WithAppUUID(appUUID string) *PublishApplicationUsingUUIDParams {
	o.SetAppUUID(appUUID)
	return o
}

// SetAppUUID adds the appUuid to the publish application using Uuid params
func (o *PublishApplicationUsingUUIDParams) SetAppUUID(appUUID string) {
	o.AppUUID = appUUID
}

// WriteToRequest writes these params to a swagger request
func (o *PublishApplicationUsingUUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param appUuid
	if err := r.SetPathParam("appUuid", o.AppUUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
