// Code generated by go-swagger; DO NOT EDIT.

package applications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/tsrob/l7portal-go/models"
)

// UpdateApplicationAPIPlanUsingUUIDReader is a Reader for the UpdateApplicationAPIPlanUsingUUID structure.
type UpdateApplicationAPIPlanUsingUUIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateApplicationAPIPlanUsingUUIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewUpdateApplicationAPIPlanUsingUUIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateApplicationAPIPlanUsingUUIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateApplicationAPIPlanUsingUUIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUpdateApplicationAPIPlanUsingUUIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateApplicationAPIPlanUsingUUIDNoContent creates a UpdateApplicationAPIPlanUsingUUIDNoContent with default headers values
func NewUpdateApplicationAPIPlanUsingUUIDNoContent() *UpdateApplicationAPIPlanUsingUUIDNoContent {
	return &UpdateApplicationAPIPlanUsingUUIDNoContent{}
}

/*
UpdateApplicationAPIPlanUsingUUIDNoContent describes a response with status code 204, with default header values.

OK, no Content to show
*/
type UpdateApplicationAPIPlanUsingUUIDNoContent struct {
}

// IsSuccess returns true when this update application Api plan using Uuid no content response has a 2xx status code
func (o *UpdateApplicationAPIPlanUsingUUIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update application Api plan using Uuid no content response has a 3xx status code
func (o *UpdateApplicationAPIPlanUsingUUIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update application Api plan using Uuid no content response has a 4xx status code
func (o *UpdateApplicationAPIPlanUsingUUIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this update application Api plan using Uuid no content response has a 5xx status code
func (o *UpdateApplicationAPIPlanUsingUUIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this update application Api plan using Uuid no content response a status code equal to that given
func (o *UpdateApplicationAPIPlanUsingUUIDNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the update application Api plan using Uuid no content response
func (o *UpdateApplicationAPIPlanUsingUUIDNoContent) Code() int {
	return 204
}

func (o *UpdateApplicationAPIPlanUsingUUIDNoContent) Error() string {
	return fmt.Sprintf("[PUT /api-management/0.1/applications/{appUuid}/api-plans][%d] updateApplicationApiPlanUsingUuidNoContent ", 204)
}

func (o *UpdateApplicationAPIPlanUsingUUIDNoContent) String() string {
	return fmt.Sprintf("[PUT /api-management/0.1/applications/{appUuid}/api-plans][%d] updateApplicationApiPlanUsingUuidNoContent ", 204)
}

func (o *UpdateApplicationAPIPlanUsingUUIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateApplicationAPIPlanUsingUUIDBadRequest creates a UpdateApplicationAPIPlanUsingUUIDBadRequest with default headers values
func NewUpdateApplicationAPIPlanUsingUUIDBadRequest() *UpdateApplicationAPIPlanUsingUUIDBadRequest {
	return &UpdateApplicationAPIPlanUsingUUIDBadRequest{}
}

/*
UpdateApplicationAPIPlanUsingUUIDBadRequest describes a response with status code 400, with default header values.

Bad Request due to a validation error.
*/
type UpdateApplicationAPIPlanUsingUUIDBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this update application Api plan using Uuid bad request response has a 2xx status code
func (o *UpdateApplicationAPIPlanUsingUUIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update application Api plan using Uuid bad request response has a 3xx status code
func (o *UpdateApplicationAPIPlanUsingUUIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update application Api plan using Uuid bad request response has a 4xx status code
func (o *UpdateApplicationAPIPlanUsingUUIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this update application Api plan using Uuid bad request response has a 5xx status code
func (o *UpdateApplicationAPIPlanUsingUUIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this update application Api plan using Uuid bad request response a status code equal to that given
func (o *UpdateApplicationAPIPlanUsingUUIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the update application Api plan using Uuid bad request response
func (o *UpdateApplicationAPIPlanUsingUUIDBadRequest) Code() int {
	return 400
}

func (o *UpdateApplicationAPIPlanUsingUUIDBadRequest) Error() string {
	return fmt.Sprintf("[PUT /api-management/0.1/applications/{appUuid}/api-plans][%d] updateApplicationApiPlanUsingUuidBadRequest  %+v", 400, o.Payload)
}

func (o *UpdateApplicationAPIPlanUsingUUIDBadRequest) String() string {
	return fmt.Sprintf("[PUT /api-management/0.1/applications/{appUuid}/api-plans][%d] updateApplicationApiPlanUsingUuidBadRequest  %+v", 400, o.Payload)
}

func (o *UpdateApplicationAPIPlanUsingUUIDBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *UpdateApplicationAPIPlanUsingUUIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateApplicationAPIPlanUsingUUIDNotFound creates a UpdateApplicationAPIPlanUsingUUIDNotFound with default headers values
func NewUpdateApplicationAPIPlanUsingUUIDNotFound() *UpdateApplicationAPIPlanUsingUUIDNotFound {
	return &UpdateApplicationAPIPlanUsingUUIDNotFound{}
}

/*
UpdateApplicationAPIPlanUsingUUIDNotFound describes a response with status code 404, with default header values.

Entity not found
*/
type UpdateApplicationAPIPlanUsingUUIDNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this update application Api plan using Uuid not found response has a 2xx status code
func (o *UpdateApplicationAPIPlanUsingUUIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update application Api plan using Uuid not found response has a 3xx status code
func (o *UpdateApplicationAPIPlanUsingUUIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update application Api plan using Uuid not found response has a 4xx status code
func (o *UpdateApplicationAPIPlanUsingUUIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this update application Api plan using Uuid not found response has a 5xx status code
func (o *UpdateApplicationAPIPlanUsingUUIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this update application Api plan using Uuid not found response a status code equal to that given
func (o *UpdateApplicationAPIPlanUsingUUIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the update application Api plan using Uuid not found response
func (o *UpdateApplicationAPIPlanUsingUUIDNotFound) Code() int {
	return 404
}

func (o *UpdateApplicationAPIPlanUsingUUIDNotFound) Error() string {
	return fmt.Sprintf("[PUT /api-management/0.1/applications/{appUuid}/api-plans][%d] updateApplicationApiPlanUsingUuidNotFound  %+v", 404, o.Payload)
}

func (o *UpdateApplicationAPIPlanUsingUUIDNotFound) String() string {
	return fmt.Sprintf("[PUT /api-management/0.1/applications/{appUuid}/api-plans][%d] updateApplicationApiPlanUsingUuidNotFound  %+v", 404, o.Payload)
}

func (o *UpdateApplicationAPIPlanUsingUUIDNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *UpdateApplicationAPIPlanUsingUUIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateApplicationAPIPlanUsingUUIDInternalServerError creates a UpdateApplicationAPIPlanUsingUUIDInternalServerError with default headers values
func NewUpdateApplicationAPIPlanUsingUUIDInternalServerError() *UpdateApplicationAPIPlanUsingUUIDInternalServerError {
	return &UpdateApplicationAPIPlanUsingUUIDInternalServerError{}
}

/*
UpdateApplicationAPIPlanUsingUUIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error. Certain fields are missing from the request.
*/
type UpdateApplicationAPIPlanUsingUUIDInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this update application Api plan using Uuid internal server error response has a 2xx status code
func (o *UpdateApplicationAPIPlanUsingUUIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update application Api plan using Uuid internal server error response has a 3xx status code
func (o *UpdateApplicationAPIPlanUsingUUIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update application Api plan using Uuid internal server error response has a 4xx status code
func (o *UpdateApplicationAPIPlanUsingUUIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this update application Api plan using Uuid internal server error response has a 5xx status code
func (o *UpdateApplicationAPIPlanUsingUUIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this update application Api plan using Uuid internal server error response a status code equal to that given
func (o *UpdateApplicationAPIPlanUsingUUIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the update application Api plan using Uuid internal server error response
func (o *UpdateApplicationAPIPlanUsingUUIDInternalServerError) Code() int {
	return 500
}

func (o *UpdateApplicationAPIPlanUsingUUIDInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /api-management/0.1/applications/{appUuid}/api-plans][%d] updateApplicationApiPlanUsingUuidInternalServerError  %+v", 500, o.Payload)
}

func (o *UpdateApplicationAPIPlanUsingUUIDInternalServerError) String() string {
	return fmt.Sprintf("[PUT /api-management/0.1/applications/{appUuid}/api-plans][%d] updateApplicationApiPlanUsingUuidInternalServerError  %+v", 500, o.Payload)
}

func (o *UpdateApplicationAPIPlanUsingUUIDInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *UpdateApplicationAPIPlanUsingUUIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
UpdateApplicationAPIPlanUsingUUIDBody update application API plan using UUID body
swagger:model UpdateApplicationAPIPlanUsingUUIDBody
*/
type UpdateApplicationAPIPlanUsingUUIDBody struct {

	// sources
	Sources []*models.ApplicationAPIPlanReference `json:"sources"`
}

// Validate validates this update application API plan using UUID body
func (o *UpdateApplicationAPIPlanUsingUUIDBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateSources(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateApplicationAPIPlanUsingUUIDBody) validateSources(formats strfmt.Registry) error {
	if swag.IsZero(o.Sources) { // not required
		return nil
	}

	for i := 0; i < len(o.Sources); i++ {
		if swag.IsZero(o.Sources[i]) { // not required
			continue
		}

		if o.Sources[i] != nil {
			if err := o.Sources[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("apiPlans" + "." + "sources" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("apiPlans" + "." + "sources" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this update application API plan using UUID body based on the context it is used
func (o *UpdateApplicationAPIPlanUsingUUIDBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateSources(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateApplicationAPIPlanUsingUUIDBody) contextValidateSources(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Sources); i++ {

		if o.Sources[i] != nil {
			if err := o.Sources[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("apiPlans" + "." + "sources" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("apiPlans" + "." + "sources" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *UpdateApplicationAPIPlanUsingUUIDBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateApplicationAPIPlanUsingUUIDBody) UnmarshalBinary(b []byte) error {
	var res UpdateApplicationAPIPlanUsingUUIDBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
