// Code generated by go-swagger; DO NOT EDIT.

package api_organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new api organizations API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for api organizations API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	PATCHAPIOrganizations(params *PATCHAPIOrganizationsParams, opts ...ClientOption) (*PATCHAPIOrganizationsNoContent, error)

	PUTAPIOrganizations(params *PUTAPIOrganizationsParams, opts ...ClientOption) (*PUTAPIOrganizationsNoContent, error)

	GetAllAPIOrganizationEntitiesUsingGET(params *GetAllAPIOrganizationEntitiesUsingGETParams, opts ...ClientOption) (*GetAllAPIOrganizationEntitiesUsingGETOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
PATCHAPIOrganizations updates the API s org access
*/
func (a *Client) PATCHAPIOrganizations(params *PATCHAPIOrganizationsParams, opts ...ClientOption) (*PATCHAPIOrganizationsNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPATCHAPIOrganizationsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PATCHApiOrganizations",
		Method:             "PATCH",
		PathPattern:        "/api-management/1.0/apis/{apiUuid}/organizations",
		ProducesMediaTypes: []string{"application/json;charset=UTF-8"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PATCHAPIOrganizationsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PATCHAPIOrganizationsNoContent)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PATCHApiOrganizations: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PUTAPIOrganizations posts API organization
*/
func (a *Client) PUTAPIOrganizations(params *PUTAPIOrganizationsParams, opts ...ClientOption) (*PUTAPIOrganizationsNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPUTAPIOrganizationsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PUTApiOrganizations",
		Method:             "PUT",
		PathPattern:        "/api-management/1.0/apis/{apiUuid}/organizations",
		ProducesMediaTypes: []string{"application/json;charset=UTF-8"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PUTAPIOrganizationsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PUTAPIOrganizationsNoContent)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PUTApiOrganizations: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAllAPIOrganizationEntitiesUsingGET gets all associated organization entities of an API

All Organization entities associated with the specified API will be retrieved.
*/
func (a *Client) GetAllAPIOrganizationEntitiesUsingGET(params *GetAllAPIOrganizationEntitiesUsingGETParams, opts ...ClientOption) (*GetAllAPIOrganizationEntitiesUsingGETOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAllAPIOrganizationEntitiesUsingGETParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getAllApiOrganizationEntitiesUsingGET",
		Method:             "GET",
		PathPattern:        "/api-management/1.0/apis/{apiUuid}/organizations",
		ProducesMediaTypes: []string{"application/json;charset=UTF-8"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetAllAPIOrganizationEntitiesUsingGETReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetAllAPIOrganizationEntitiesUsingGETOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getAllApiOrganizationEntitiesUsingGET: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
