// Code generated by go-swagger; DO NOT EDIT.

package api_catalogs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPICatalogMarkDownAssetByNavTitleParams creates a new GetAPICatalogMarkDownAssetByNavTitleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPICatalogMarkDownAssetByNavTitleParams() *GetAPICatalogMarkDownAssetByNavTitleParams {
	return &GetAPICatalogMarkDownAssetByNavTitleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPICatalogMarkDownAssetByNavTitleParamsWithTimeout creates a new GetAPICatalogMarkDownAssetByNavTitleParams object
// with the ability to set a timeout on a request.
func NewGetAPICatalogMarkDownAssetByNavTitleParamsWithTimeout(timeout time.Duration) *GetAPICatalogMarkDownAssetByNavTitleParams {
	return &GetAPICatalogMarkDownAssetByNavTitleParams{
		timeout: timeout,
	}
}

// NewGetAPICatalogMarkDownAssetByNavTitleParamsWithContext creates a new GetAPICatalogMarkDownAssetByNavTitleParams object
// with the ability to set a context for a request.
func NewGetAPICatalogMarkDownAssetByNavTitleParamsWithContext(ctx context.Context) *GetAPICatalogMarkDownAssetByNavTitleParams {
	return &GetAPICatalogMarkDownAssetByNavTitleParams{
		Context: ctx,
	}
}

// NewGetAPICatalogMarkDownAssetByNavTitleParamsWithHTTPClient creates a new GetAPICatalogMarkDownAssetByNavTitleParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPICatalogMarkDownAssetByNavTitleParamsWithHTTPClient(client *http.Client) *GetAPICatalogMarkDownAssetByNavTitleParams {
	return &GetAPICatalogMarkDownAssetByNavTitleParams{
		HTTPClient: client,
	}
}

/*
GetAPICatalogMarkDownAssetByNavTitleParams contains all the parameters to send to the API endpoint

	for the get Api catalog mark down asset by nav title operation.

	Typically these are written to a http.Request.
*/
type GetAPICatalogMarkDownAssetByNavTitleParams struct {

	/* APIUUID.

	   The UUID of the API associated with the document.
	*/
	APIUUID string

	/* Locale.

	   The locale for the document. For example, en-US, fr-FR, and fr-CA. The default value of locale is en-US.
	*/
	Locale *string

	/* Navtitle.

	   The navigation title for the document.
	*/
	Navtitle string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get Api catalog mark down asset by nav title params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPICatalogMarkDownAssetByNavTitleParams) WithDefaults() *GetAPICatalogMarkDownAssetByNavTitleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get Api catalog mark down asset by nav title params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPICatalogMarkDownAssetByNavTitleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get Api catalog mark down asset by nav title params
func (o *GetAPICatalogMarkDownAssetByNavTitleParams) WithTimeout(timeout time.Duration) *GetAPICatalogMarkDownAssetByNavTitleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get Api catalog mark down asset by nav title params
func (o *GetAPICatalogMarkDownAssetByNavTitleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get Api catalog mark down asset by nav title params
func (o *GetAPICatalogMarkDownAssetByNavTitleParams) WithContext(ctx context.Context) *GetAPICatalogMarkDownAssetByNavTitleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get Api catalog mark down asset by nav title params
func (o *GetAPICatalogMarkDownAssetByNavTitleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get Api catalog mark down asset by nav title params
func (o *GetAPICatalogMarkDownAssetByNavTitleParams) WithHTTPClient(client *http.Client) *GetAPICatalogMarkDownAssetByNavTitleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get Api catalog mark down asset by nav title params
func (o *GetAPICatalogMarkDownAssetByNavTitleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIUUID adds the aPIUUID to the get Api catalog mark down asset by nav title params
func (o *GetAPICatalogMarkDownAssetByNavTitleParams) WithAPIUUID(aPIUUID string) *GetAPICatalogMarkDownAssetByNavTitleParams {
	o.SetAPIUUID(aPIUUID)
	return o
}

// SetAPIUUID adds the apiUuid to the get Api catalog mark down asset by nav title params
func (o *GetAPICatalogMarkDownAssetByNavTitleParams) SetAPIUUID(aPIUUID string) {
	o.APIUUID = aPIUUID
}

// WithLocale adds the locale to the get Api catalog mark down asset by nav title params
func (o *GetAPICatalogMarkDownAssetByNavTitleParams) WithLocale(locale *string) *GetAPICatalogMarkDownAssetByNavTitleParams {
	o.SetLocale(locale)
	return o
}

// SetLocale adds the locale to the get Api catalog mark down asset by nav title params
func (o *GetAPICatalogMarkDownAssetByNavTitleParams) SetLocale(locale *string) {
	o.Locale = locale
}

// WithNavtitle adds the navtitle to the get Api catalog mark down asset by nav title params
func (o *GetAPICatalogMarkDownAssetByNavTitleParams) WithNavtitle(navtitle string) *GetAPICatalogMarkDownAssetByNavTitleParams {
	o.SetNavtitle(navtitle)
	return o
}

// SetNavtitle adds the navtitle to the get Api catalog mark down asset by nav title params
func (o *GetAPICatalogMarkDownAssetByNavTitleParams) SetNavtitle(navtitle string) {
	o.Navtitle = navtitle
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPICatalogMarkDownAssetByNavTitleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param apiUuid
	if err := r.SetPathParam("apiUuid", o.APIUUID); err != nil {
		return err
	}

	if o.Locale != nil {

		// query param locale
		var qrLocale string

		if o.Locale != nil {
			qrLocale = *o.Locale
		}
		qLocale := qrLocale
		if qLocale != "" {

			if err := r.SetQueryParam("locale", qLocale); err != nil {
				return err
			}
		}
	}

	// path param navtitle
	if err := r.SetPathParam("navtitle", o.Navtitle); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
