// Code generated by go-swagger; DO NOT EDIT.

package api_catalogs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tsrob/l7portal-go/models"
)

// GetAPICatalogsReader is a Reader for the GetAPICatalogs structure.
type GetAPICatalogsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPICatalogsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPICatalogsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPICatalogsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPICatalogsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPICatalogsOK creates a GetAPICatalogsOK with default headers values
func NewGetAPICatalogsOK() *GetAPICatalogsOK {
	return &GetAPICatalogsOK{}
}

/*
GetAPICatalogsOK describes a response with status code 200, with default header values.

GetAPICatalogsOK get Api catalogs o k
*/
type GetAPICatalogsOK struct {
	Payload *models.APICatalogsDto
}

// IsSuccess returns true when this get Api catalogs o k response has a 2xx status code
func (o *GetAPICatalogsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api catalogs o k response has a 3xx status code
func (o *GetAPICatalogsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api catalogs o k response has a 4xx status code
func (o *GetAPICatalogsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api catalogs o k response has a 5xx status code
func (o *GetAPICatalogsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api catalogs o k response a status code equal to that given
func (o *GetAPICatalogsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api catalogs o k response
func (o *GetAPICatalogsOK) Code() int {
	return 200
}

func (o *GetAPICatalogsOK) Error() string {
	return fmt.Sprintf("[GET /api-management/1.0/api-catalogs][%d] getApiCatalogsOK  %+v", 200, o.Payload)
}

func (o *GetAPICatalogsOK) String() string {
	return fmt.Sprintf("[GET /api-management/1.0/api-catalogs][%d] getApiCatalogsOK  %+v", 200, o.Payload)
}

func (o *GetAPICatalogsOK) GetPayload() *models.APICatalogsDto {
	return o.Payload
}

func (o *GetAPICatalogsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APICatalogsDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPICatalogsBadRequest creates a GetAPICatalogsBadRequest with default headers values
func NewGetAPICatalogsBadRequest() *GetAPICatalogsBadRequest {
	return &GetAPICatalogsBadRequest{}
}

/*
GetAPICatalogsBadRequest describes a response with status code 400, with default header values.

Bad Request due to Invalid Parameters.
*/
type GetAPICatalogsBadRequest struct {
	Payload *models.LongerError
}

// IsSuccess returns true when this get Api catalogs bad request response has a 2xx status code
func (o *GetAPICatalogsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api catalogs bad request response has a 3xx status code
func (o *GetAPICatalogsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api catalogs bad request response has a 4xx status code
func (o *GetAPICatalogsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api catalogs bad request response has a 5xx status code
func (o *GetAPICatalogsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api catalogs bad request response a status code equal to that given
func (o *GetAPICatalogsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get Api catalogs bad request response
func (o *GetAPICatalogsBadRequest) Code() int {
	return 400
}

func (o *GetAPICatalogsBadRequest) Error() string {
	return fmt.Sprintf("[GET /api-management/1.0/api-catalogs][%d] getApiCatalogsBadRequest  %+v", 400, o.Payload)
}

func (o *GetAPICatalogsBadRequest) String() string {
	return fmt.Sprintf("[GET /api-management/1.0/api-catalogs][%d] getApiCatalogsBadRequest  %+v", 400, o.Payload)
}

func (o *GetAPICatalogsBadRequest) GetPayload() *models.LongerError {
	return o.Payload
}

func (o *GetAPICatalogsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LongerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPICatalogsInternalServerError creates a GetAPICatalogsInternalServerError with default headers values
func NewGetAPICatalogsInternalServerError() *GetAPICatalogsInternalServerError {
	return &GetAPICatalogsInternalServerError{}
}

/*
GetAPICatalogsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error. Certain fields are missing from the request.
*/
type GetAPICatalogsInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this get Api catalogs internal server error response has a 2xx status code
func (o *GetAPICatalogsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api catalogs internal server error response has a 3xx status code
func (o *GetAPICatalogsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api catalogs internal server error response has a 4xx status code
func (o *GetAPICatalogsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api catalogs internal server error response has a 5xx status code
func (o *GetAPICatalogsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api catalogs internal server error response a status code equal to that given
func (o *GetAPICatalogsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api catalogs internal server error response
func (o *GetAPICatalogsInternalServerError) Code() int {
	return 500
}

func (o *GetAPICatalogsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api-management/1.0/api-catalogs][%d] getApiCatalogsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetAPICatalogsInternalServerError) String() string {
	return fmt.Sprintf("[GET /api-management/1.0/api-catalogs][%d] getApiCatalogsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetAPICatalogsInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetAPICatalogsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
