// Code generated by go-swagger; DO NOT EDIT.

package apis

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAPIUsingDELETEParams creates a new DeleteAPIUsingDELETEParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAPIUsingDELETEParams() *DeleteAPIUsingDELETEParams {
	return &DeleteAPIUsingDELETEParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPIUsingDELETEParamsWithTimeout creates a new DeleteAPIUsingDELETEParams object
// with the ability to set a timeout on a request.
func NewDeleteAPIUsingDELETEParamsWithTimeout(timeout time.Duration) *DeleteAPIUsingDELETEParams {
	return &DeleteAPIUsingDELETEParams{
		timeout: timeout,
	}
}

// NewDeleteAPIUsingDELETEParamsWithContext creates a new DeleteAPIUsingDELETEParams object
// with the ability to set a context for a request.
func NewDeleteAPIUsingDELETEParamsWithContext(ctx context.Context) *DeleteAPIUsingDELETEParams {
	return &DeleteAPIUsingDELETEParams{
		Context: ctx,
	}
}

// NewDeleteAPIUsingDELETEParamsWithHTTPClient creates a new DeleteAPIUsingDELETEParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAPIUsingDELETEParamsWithHTTPClient(client *http.Client) *DeleteAPIUsingDELETEParams {
	return &DeleteAPIUsingDELETEParams{
		HTTPClient: client,
	}
}

/*
DeleteAPIUsingDELETEParams contains all the parameters to send to the API endpoint

	for the delete Api using d e l e t e operation.

	Typically these are written to a http.Request.
*/
type DeleteAPIUsingDELETEParams struct {

	/* APIUUID.

	   uuid
	*/
	APIUUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete Api using d e l e t e params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIUsingDELETEParams) WithDefaults() *DeleteAPIUsingDELETEParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete Api using d e l e t e params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIUsingDELETEParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete Api using d e l e t e params
func (o *DeleteAPIUsingDELETEParams) WithTimeout(timeout time.Duration) *DeleteAPIUsingDELETEParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete Api using d e l e t e params
func (o *DeleteAPIUsingDELETEParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete Api using d e l e t e params
func (o *DeleteAPIUsingDELETEParams) WithContext(ctx context.Context) *DeleteAPIUsingDELETEParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete Api using d e l e t e params
func (o *DeleteAPIUsingDELETEParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete Api using d e l e t e params
func (o *DeleteAPIUsingDELETEParams) WithHTTPClient(client *http.Client) *DeleteAPIUsingDELETEParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete Api using d e l e t e params
func (o *DeleteAPIUsingDELETEParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIUUID adds the aPIUUID to the delete Api using d e l e t e params
func (o *DeleteAPIUsingDELETEParams) WithAPIUUID(aPIUUID string) *DeleteAPIUsingDELETEParams {
	o.SetAPIUUID(aPIUUID)
	return o
}

// SetAPIUUID adds the apiUuid to the delete Api using d e l e t e params
func (o *DeleteAPIUsingDELETEParams) SetAPIUUID(aPIUUID string) {
	o.APIUUID = aPIUUID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPIUsingDELETEParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param apiUuid
	if err := r.SetPathParam("apiUuid", o.APIUUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
