// Code generated by go-swagger; DO NOT EDIT.

package apis

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAssetFileUsingGETParams creates a new GetAssetFileUsingGETParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAssetFileUsingGETParams() *GetAssetFileUsingGETParams {
	return &GetAssetFileUsingGETParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAssetFileUsingGETParamsWithTimeout creates a new GetAssetFileUsingGETParams object
// with the ability to set a timeout on a request.
func NewGetAssetFileUsingGETParamsWithTimeout(timeout time.Duration) *GetAssetFileUsingGETParams {
	return &GetAssetFileUsingGETParams{
		timeout: timeout,
	}
}

// NewGetAssetFileUsingGETParamsWithContext creates a new GetAssetFileUsingGETParams object
// with the ability to set a context for a request.
func NewGetAssetFileUsingGETParamsWithContext(ctx context.Context) *GetAssetFileUsingGETParams {
	return &GetAssetFileUsingGETParams{
		Context: ctx,
	}
}

// NewGetAssetFileUsingGETParamsWithHTTPClient creates a new GetAssetFileUsingGETParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAssetFileUsingGETParamsWithHTTPClient(client *http.Client) *GetAssetFileUsingGETParams {
	return &GetAssetFileUsingGETParams{
		HTTPClient: client,
	}
}

/*
GetAssetFileUsingGETParams contains all the parameters to send to the API endpoint

	for the get asset file using g e t operation.

	Typically these are written to a http.Request.
*/
type GetAssetFileUsingGETParams struct {

	/* APIUUID.

	   apiUuid
	*/
	APIUUID string

	/* UUID.

	   uuid
	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get asset file using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAssetFileUsingGETParams) WithDefaults() *GetAssetFileUsingGETParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get asset file using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAssetFileUsingGETParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get asset file using g e t params
func (o *GetAssetFileUsingGETParams) WithTimeout(timeout time.Duration) *GetAssetFileUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get asset file using g e t params
func (o *GetAssetFileUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get asset file using g e t params
func (o *GetAssetFileUsingGETParams) WithContext(ctx context.Context) *GetAssetFileUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get asset file using g e t params
func (o *GetAssetFileUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get asset file using g e t params
func (o *GetAssetFileUsingGETParams) WithHTTPClient(client *http.Client) *GetAssetFileUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get asset file using g e t params
func (o *GetAssetFileUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIUUID adds the aPIUUID to the get asset file using g e t params
func (o *GetAssetFileUsingGETParams) WithAPIUUID(aPIUUID string) *GetAssetFileUsingGETParams {
	o.SetAPIUUID(aPIUUID)
	return o
}

// SetAPIUUID adds the apiUuid to the get asset file using g e t params
func (o *GetAssetFileUsingGETParams) SetAPIUUID(aPIUUID string) {
	o.APIUUID = aPIUUID
}

// WithUUID adds the uuid to the get asset file using g e t params
func (o *GetAssetFileUsingGETParams) WithUUID(uuid string) *GetAssetFileUsingGETParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the get asset file using g e t params
func (o *GetAssetFileUsingGETParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *GetAssetFileUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param apiUuid
	if err := r.SetPathParam("apiUuid", o.APIUUID); err != nil {
		return err
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
