// Code generated by go-swagger; DO NOT EDIT.

package auditing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new auditing API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for auditing API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetAudits(params *GetAuditsParams, opts ...ClientOption) (*GetAuditsOK, error)

	GetAuditsExport(params *GetAuditsExportParams, writer io.Writer, opts ...ClientOption) (*GetAuditsExportOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetAudits returns a filtered list of audit logs

Returns a filtered and sorted list of Audit Log entries.
*/
func (a *Client) GetAudits(params *GetAuditsParams, opts ...ClientOption) (*GetAuditsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAuditsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getAudits",
		Method:             "GET",
		PathPattern:        "/tenant-admin/1.0/audits",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetAuditsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetAuditsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getAudits: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAuditsExport exports a list of audit logs

Export a sorted list of Audit Log entries.
*/
func (a *Client) GetAuditsExport(params *GetAuditsExportParams, writer io.Writer, opts ...ClientOption) (*GetAuditsExportOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAuditsExportParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getAuditsExport",
		Method:             "GET",
		PathPattern:        "/tenant-admin/1.0/audits/export",
		ProducesMediaTypes: []string{"application/octet-stream"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetAuditsExportReader{formats: a.formats, writer: writer},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetAuditsExportOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getAuditsExport: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
