// Code generated by go-swagger; DO NOT EDIT.

package auditing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tsrob/l7portal-go/models"
)

// GetAuditsExportReader is a Reader for the GetAuditsExport structure.
type GetAuditsExportReader struct {
	formats strfmt.Registry
	writer  io.Writer
}

// ReadResponse reads a server response into the received o.
func (o *GetAuditsExportReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAuditsExportOK(o.writer)
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAuditsExportBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAuditsExportInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAuditsExportOK creates a GetAuditsExportOK with default headers values
func NewGetAuditsExportOK(writer io.Writer) *GetAuditsExportOK {
	return &GetAuditsExportOK{

		Payload: writer,
	}
}

/*
GetAuditsExportOK describes a response with status code 200, with default header values.

GetAuditsExportOK get audits export o k
*/
type GetAuditsExportOK struct {
	Payload io.Writer
}

// IsSuccess returns true when this get audits export o k response has a 2xx status code
func (o *GetAuditsExportOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get audits export o k response has a 3xx status code
func (o *GetAuditsExportOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get audits export o k response has a 4xx status code
func (o *GetAuditsExportOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get audits export o k response has a 5xx status code
func (o *GetAuditsExportOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get audits export o k response a status code equal to that given
func (o *GetAuditsExportOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get audits export o k response
func (o *GetAuditsExportOK) Code() int {
	return 200
}

func (o *GetAuditsExportOK) Error() string {
	return fmt.Sprintf("[GET /tenant-admin/1.0/audits/export][%d] getAuditsExportOK  %+v", 200, o.Payload)
}

func (o *GetAuditsExportOK) String() string {
	return fmt.Sprintf("[GET /tenant-admin/1.0/audits/export][%d] getAuditsExportOK  %+v", 200, o.Payload)
}

func (o *GetAuditsExportOK) GetPayload() io.Writer {
	return o.Payload
}

func (o *GetAuditsExportOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAuditsExportBadRequest creates a GetAuditsExportBadRequest with default headers values
func NewGetAuditsExportBadRequest() *GetAuditsExportBadRequest {
	return &GetAuditsExportBadRequest{}
}

/*
GetAuditsExportBadRequest describes a response with status code 400, with default header values.

Bad Request due to a validation error.
*/
type GetAuditsExportBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this get audits export bad request response has a 2xx status code
func (o *GetAuditsExportBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get audits export bad request response has a 3xx status code
func (o *GetAuditsExportBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get audits export bad request response has a 4xx status code
func (o *GetAuditsExportBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get audits export bad request response has a 5xx status code
func (o *GetAuditsExportBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get audits export bad request response a status code equal to that given
func (o *GetAuditsExportBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get audits export bad request response
func (o *GetAuditsExportBadRequest) Code() int {
	return 400
}

func (o *GetAuditsExportBadRequest) Error() string {
	return fmt.Sprintf("[GET /tenant-admin/1.0/audits/export][%d] getAuditsExportBadRequest  %+v", 400, o.Payload)
}

func (o *GetAuditsExportBadRequest) String() string {
	return fmt.Sprintf("[GET /tenant-admin/1.0/audits/export][%d] getAuditsExportBadRequest  %+v", 400, o.Payload)
}

func (o *GetAuditsExportBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetAuditsExportBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAuditsExportInternalServerError creates a GetAuditsExportInternalServerError with default headers values
func NewGetAuditsExportInternalServerError() *GetAuditsExportInternalServerError {
	return &GetAuditsExportInternalServerError{}
}

/*
GetAuditsExportInternalServerError describes a response with status code 500, with default header values.

Internal Server Error. Certain fields are missing from the request.
*/
type GetAuditsExportInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this get audits export internal server error response has a 2xx status code
func (o *GetAuditsExportInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get audits export internal server error response has a 3xx status code
func (o *GetAuditsExportInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get audits export internal server error response has a 4xx status code
func (o *GetAuditsExportInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get audits export internal server error response has a 5xx status code
func (o *GetAuditsExportInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get audits export internal server error response a status code equal to that given
func (o *GetAuditsExportInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get audits export internal server error response
func (o *GetAuditsExportInternalServerError) Code() int {
	return 500
}

func (o *GetAuditsExportInternalServerError) Error() string {
	return fmt.Sprintf("[GET /tenant-admin/1.0/audits/export][%d] getAuditsExportInternalServerError  %+v", 500, o.Payload)
}

func (o *GetAuditsExportInternalServerError) String() string {
	return fmt.Sprintf("[GET /tenant-admin/1.0/audits/export][%d] getAuditsExportInternalServerError  %+v", 500, o.Payload)
}

func (o *GetAuditsExportInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetAuditsExportInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
