// Code generated by go-swagger; DO NOT EDIT.

package proxies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateDeploymentTypeUsingPUTReader is a Reader for the UpdateDeploymentTypeUsingPUT structure.
type UpdateDeploymentTypeUsingPUTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateDeploymentTypeUsingPUTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewUpdateDeploymentTypeUsingPUTNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateDeploymentTypeUsingPUTNoContent creates a UpdateDeploymentTypeUsingPUTNoContent with default headers values
func NewUpdateDeploymentTypeUsingPUTNoContent() *UpdateDeploymentTypeUsingPUTNoContent {
	return &UpdateDeploymentTypeUsingPUTNoContent{}
}

/*
UpdateDeploymentTypeUsingPUTNoContent describes a response with status code 204, with default header values.

No Content
*/
type UpdateDeploymentTypeUsingPUTNoContent struct {
}

// IsSuccess returns true when this update deployment type using p u t no content response has a 2xx status code
func (o *UpdateDeploymentTypeUsingPUTNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update deployment type using p u t no content response has a 3xx status code
func (o *UpdateDeploymentTypeUsingPUTNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update deployment type using p u t no content response has a 4xx status code
func (o *UpdateDeploymentTypeUsingPUTNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this update deployment type using p u t no content response has a 5xx status code
func (o *UpdateDeploymentTypeUsingPUTNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this update deployment type using p u t no content response a status code equal to that given
func (o *UpdateDeploymentTypeUsingPUTNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the update deployment type using p u t no content response
func (o *UpdateDeploymentTypeUsingPUTNoContent) Code() int {
	return 204
}

func (o *UpdateDeploymentTypeUsingPUTNoContent) Error() string {
	return fmt.Sprintf("[PUT /deployments/0.1/proxies/{uuid}/deployment-type/{entity}][%d] updateDeploymentTypeUsingPUTNoContent ", 204)
}

func (o *UpdateDeploymentTypeUsingPUTNoContent) String() string {
	return fmt.Sprintf("[PUT /deployments/0.1/proxies/{uuid}/deployment-type/{entity}][%d] updateDeploymentTypeUsingPUTNoContent ", 204)
}

func (o *UpdateDeploymentTypeUsingPUTNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
