// Code generated by go-swagger; DO NOT EDIT.

package api_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tsrob/l7portal-go/models"
)

// GetAPIGroupReader is a Reader for the GetAPIGroup structure.
type GetAPIGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetAPIGroupNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPIGroupOK creates a GetAPIGroupOK with default headers values
func NewGetAPIGroupOK() *GetAPIGroupOK {
	return &GetAPIGroupOK{}
}

/*
GetAPIGroupOK describes a response with status code 200, with default header values.

GetAPIGroupOK get Api group o k
*/
type GetAPIGroupOK struct {
	Payload *models.APIGroup
}

// IsSuccess returns true when this get Api group o k response has a 2xx status code
func (o *GetAPIGroupOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api group o k response has a 3xx status code
func (o *GetAPIGroupOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api group o k response has a 4xx status code
func (o *GetAPIGroupOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api group o k response has a 5xx status code
func (o *GetAPIGroupOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api group o k response a status code equal to that given
func (o *GetAPIGroupOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api group o k response
func (o *GetAPIGroupOK) Code() int {
	return 200
}

func (o *GetAPIGroupOK) Error() string {
	return fmt.Sprintf("[GET /api-management/1.0/api-groups/{uuid}][%d] getApiGroupOK  %+v", 200, o.Payload)
}

func (o *GetAPIGroupOK) String() string {
	return fmt.Sprintf("[GET /api-management/1.0/api-groups/{uuid}][%d] getApiGroupOK  %+v", 200, o.Payload)
}

func (o *GetAPIGroupOK) GetPayload() *models.APIGroup {
	return o.Payload
}

func (o *GetAPIGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIGroupNotFound creates a GetAPIGroupNotFound with default headers values
func NewGetAPIGroupNotFound() *GetAPIGroupNotFound {
	return &GetAPIGroupNotFound{}
}

/*
GetAPIGroupNotFound describes a response with status code 404, with default header values.

Entity not found
*/
type GetAPIGroupNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this get Api group not found response has a 2xx status code
func (o *GetAPIGroupNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api group not found response has a 3xx status code
func (o *GetAPIGroupNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api group not found response has a 4xx status code
func (o *GetAPIGroupNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api group not found response has a 5xx status code
func (o *GetAPIGroupNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api group not found response a status code equal to that given
func (o *GetAPIGroupNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get Api group not found response
func (o *GetAPIGroupNotFound) Code() int {
	return 404
}

func (o *GetAPIGroupNotFound) Error() string {
	return fmt.Sprintf("[GET /api-management/1.0/api-groups/{uuid}][%d] getApiGroupNotFound  %+v", 404, o.Payload)
}

func (o *GetAPIGroupNotFound) String() string {
	return fmt.Sprintf("[GET /api-management/1.0/api-groups/{uuid}][%d] getApiGroupNotFound  %+v", 404, o.Payload)
}

func (o *GetAPIGroupNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetAPIGroupNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
