// Code generated by go-swagger; DO NOT EDIT.

package api_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIGroupsParams creates a new GetAPIGroupsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIGroupsParams() *GetAPIGroupsParams {
	return &GetAPIGroupsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIGroupsParamsWithTimeout creates a new GetAPIGroupsParams object
// with the ability to set a timeout on a request.
func NewGetAPIGroupsParamsWithTimeout(timeout time.Duration) *GetAPIGroupsParams {
	return &GetAPIGroupsParams{
		timeout: timeout,
	}
}

// NewGetAPIGroupsParamsWithContext creates a new GetAPIGroupsParams object
// with the ability to set a context for a request.
func NewGetAPIGroupsParamsWithContext(ctx context.Context) *GetAPIGroupsParams {
	return &GetAPIGroupsParams{
		Context: ctx,
	}
}

// NewGetAPIGroupsParamsWithHTTPClient creates a new GetAPIGroupsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIGroupsParamsWithHTTPClient(client *http.Client) *GetAPIGroupsParams {
	return &GetAPIGroupsParams{
		HTTPClient: client,
	}
}

/*
GetAPIGroupsParams contains all the parameters to send to the API endpoint

	for the get Api groups operation.

	Typically these are written to a http.Request.
*/
type GetAPIGroupsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get Api groups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIGroupsParams) WithDefaults() *GetAPIGroupsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get Api groups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIGroupsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get Api groups params
func (o *GetAPIGroupsParams) WithTimeout(timeout time.Duration) *GetAPIGroupsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get Api groups params
func (o *GetAPIGroupsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get Api groups params
func (o *GetAPIGroupsParams) WithContext(ctx context.Context) *GetAPIGroupsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get Api groups params
func (o *GetAPIGroupsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get Api groups params
func (o *GetAPIGroupsParams) WithHTTPClient(client *http.Client) *GetAPIGroupsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get Api groups params
func (o *GetAPIGroupsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIGroupsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
