// Code generated by go-swagger; DO NOT EDIT.

package api_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tsrob/l7portal-go/models"
)

// GetAPIGroupAPIMappingReader is a Reader for the GetAPIGroupAPIMapping structure.
type GetAPIGroupAPIMappingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIGroupAPIMappingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIGroupAPIMappingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetAPIGroupAPIMappingNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPIGroupAPIMappingOK creates a GetAPIGroupAPIMappingOK with default headers values
func NewGetAPIGroupAPIMappingOK() *GetAPIGroupAPIMappingOK {
	return &GetAPIGroupAPIMappingOK{}
}

/*
GetAPIGroupAPIMappingOK describes a response with status code 200, with default header values.

GetAPIGroupAPIMappingOK get Api group Api mapping o k
*/
type GetAPIGroupAPIMappingOK struct {
	Payload models.APIGroupApis
}

// IsSuccess returns true when this get Api group Api mapping o k response has a 2xx status code
func (o *GetAPIGroupAPIMappingOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api group Api mapping o k response has a 3xx status code
func (o *GetAPIGroupAPIMappingOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api group Api mapping o k response has a 4xx status code
func (o *GetAPIGroupAPIMappingOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api group Api mapping o k response has a 5xx status code
func (o *GetAPIGroupAPIMappingOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api group Api mapping o k response a status code equal to that given
func (o *GetAPIGroupAPIMappingOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api group Api mapping o k response
func (o *GetAPIGroupAPIMappingOK) Code() int {
	return 200
}

func (o *GetAPIGroupAPIMappingOK) Error() string {
	return fmt.Sprintf("[GET /api-management/1.0/api-groups/{uuid}/apis][%d] getApiGroupApiMappingOK  %+v", 200, o.Payload)
}

func (o *GetAPIGroupAPIMappingOK) String() string {
	return fmt.Sprintf("[GET /api-management/1.0/api-groups/{uuid}/apis][%d] getApiGroupApiMappingOK  %+v", 200, o.Payload)
}

func (o *GetAPIGroupAPIMappingOK) GetPayload() models.APIGroupApis {
	return o.Payload
}

func (o *GetAPIGroupAPIMappingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIGroupAPIMappingNotFound creates a GetAPIGroupAPIMappingNotFound with default headers values
func NewGetAPIGroupAPIMappingNotFound() *GetAPIGroupAPIMappingNotFound {
	return &GetAPIGroupAPIMappingNotFound{}
}

/*
GetAPIGroupAPIMappingNotFound describes a response with status code 404, with default header values.

Entity not found
*/
type GetAPIGroupAPIMappingNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this get Api group Api mapping not found response has a 2xx status code
func (o *GetAPIGroupAPIMappingNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api group Api mapping not found response has a 3xx status code
func (o *GetAPIGroupAPIMappingNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api group Api mapping not found response has a 4xx status code
func (o *GetAPIGroupAPIMappingNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api group Api mapping not found response has a 5xx status code
func (o *GetAPIGroupAPIMappingNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api group Api mapping not found response a status code equal to that given
func (o *GetAPIGroupAPIMappingNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get Api group Api mapping not found response
func (o *GetAPIGroupAPIMappingNotFound) Code() int {
	return 404
}

func (o *GetAPIGroupAPIMappingNotFound) Error() string {
	return fmt.Sprintf("[GET /api-management/1.0/api-groups/{uuid}/apis][%d] getApiGroupApiMappingNotFound  %+v", 404, o.Payload)
}

func (o *GetAPIGroupAPIMappingNotFound) String() string {
	return fmt.Sprintf("[GET /api-management/1.0/api-groups/{uuid}/apis][%d] getApiGroupApiMappingNotFound  %+v", 404, o.Payload)
}

func (o *GetAPIGroupAPIMappingNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetAPIGroupAPIMappingNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
