// Code generated by go-swagger; DO NOT EDIT.

package api_deployments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIDeploymentUsingGET1Params creates a new GetAPIDeploymentUsingGET1Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIDeploymentUsingGET1Params() *GetAPIDeploymentUsingGET1Params {
	return &GetAPIDeploymentUsingGET1Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIDeploymentUsingGET1ParamsWithTimeout creates a new GetAPIDeploymentUsingGET1Params object
// with the ability to set a timeout on a request.
func NewGetAPIDeploymentUsingGET1ParamsWithTimeout(timeout time.Duration) *GetAPIDeploymentUsingGET1Params {
	return &GetAPIDeploymentUsingGET1Params{
		timeout: timeout,
	}
}

// NewGetAPIDeploymentUsingGET1ParamsWithContext creates a new GetAPIDeploymentUsingGET1Params object
// with the ability to set a context for a request.
func NewGetAPIDeploymentUsingGET1ParamsWithContext(ctx context.Context) *GetAPIDeploymentUsingGET1Params {
	return &GetAPIDeploymentUsingGET1Params{
		Context: ctx,
	}
}

// NewGetAPIDeploymentUsingGET1ParamsWithHTTPClient creates a new GetAPIDeploymentUsingGET1Params object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIDeploymentUsingGET1ParamsWithHTTPClient(client *http.Client) *GetAPIDeploymentUsingGET1Params {
	return &GetAPIDeploymentUsingGET1Params{
		HTTPClient: client,
	}
}

/*
GetAPIDeploymentUsingGET1Params contains all the parameters to send to the API endpoint

	for the get Api deployment using g e t 1 operation.

	Typically these are written to a http.Request.
*/
type GetAPIDeploymentUsingGET1Params struct {

	/* APIUUID.

	   The API UUID.
	*/
	APIUUID string

	/* ProxyUUID.

	   The proxy UUID.
	*/
	ProxyUUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get Api deployment using g e t 1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIDeploymentUsingGET1Params) WithDefaults() *GetAPIDeploymentUsingGET1Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get Api deployment using g e t 1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIDeploymentUsingGET1Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get Api deployment using g e t 1 params
func (o *GetAPIDeploymentUsingGET1Params) WithTimeout(timeout time.Duration) *GetAPIDeploymentUsingGET1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get Api deployment using g e t 1 params
func (o *GetAPIDeploymentUsingGET1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get Api deployment using g e t 1 params
func (o *GetAPIDeploymentUsingGET1Params) WithContext(ctx context.Context) *GetAPIDeploymentUsingGET1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get Api deployment using g e t 1 params
func (o *GetAPIDeploymentUsingGET1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get Api deployment using g e t 1 params
func (o *GetAPIDeploymentUsingGET1Params) WithHTTPClient(client *http.Client) *GetAPIDeploymentUsingGET1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get Api deployment using g e t 1 params
func (o *GetAPIDeploymentUsingGET1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIUUID adds the aPIUUID to the get Api deployment using g e t 1 params
func (o *GetAPIDeploymentUsingGET1Params) WithAPIUUID(aPIUUID string) *GetAPIDeploymentUsingGET1Params {
	o.SetAPIUUID(aPIUUID)
	return o
}

// SetAPIUUID adds the apiUuid to the get Api deployment using g e t 1 params
func (o *GetAPIDeploymentUsingGET1Params) SetAPIUUID(aPIUUID string) {
	o.APIUUID = aPIUUID
}

// WithProxyUUID adds the proxyUUID to the get Api deployment using g e t 1 params
func (o *GetAPIDeploymentUsingGET1Params) WithProxyUUID(proxyUUID string) *GetAPIDeploymentUsingGET1Params {
	o.SetProxyUUID(proxyUUID)
	return o
}

// SetProxyUUID adds the proxyUuid to the get Api deployment using g e t 1 params
func (o *GetAPIDeploymentUsingGET1Params) SetProxyUUID(proxyUUID string) {
	o.ProxyUUID = proxyUUID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIDeploymentUsingGET1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param apiUuid
	if err := r.SetPathParam("apiUuid", o.APIUUID); err != nil {
		return err
	}

	// path param proxyUuid
	if err := r.SetPathParam("proxyUuid", o.ProxyUUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
