// Code generated by go-swagger; DO NOT EDIT.

package api_plans

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tsrob/l7portal-go/models"
)

// GetAPIPlanAPIUsingGET1Reader is a Reader for the GetAPIPlanAPIUsingGET1 structure.
type GetAPIPlanAPIUsingGET1Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIPlanAPIUsingGET1Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIPlanAPIUsingGET1OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetAPIPlanAPIUsingGET1NotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIPlanAPIUsingGET1InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPIPlanAPIUsingGET1OK creates a GetAPIPlanAPIUsingGET1OK with default headers values
func NewGetAPIPlanAPIUsingGET1OK() *GetAPIPlanAPIUsingGET1OK {
	return &GetAPIPlanAPIUsingGET1OK{}
}

/*
GetAPIPlanAPIUsingGET1OK describes a response with status code 200, with default header values.

Success
*/
type GetAPIPlanAPIUsingGET1OK struct {
	Payload int64
}

// IsSuccess returns true when this get Api plan Api using g e t1 o k response has a 2xx status code
func (o *GetAPIPlanAPIUsingGET1OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api plan Api using g e t1 o k response has a 3xx status code
func (o *GetAPIPlanAPIUsingGET1OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api plan Api using g e t1 o k response has a 4xx status code
func (o *GetAPIPlanAPIUsingGET1OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api plan Api using g e t1 o k response has a 5xx status code
func (o *GetAPIPlanAPIUsingGET1OK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api plan Api using g e t1 o k response a status code equal to that given
func (o *GetAPIPlanAPIUsingGET1OK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api plan Api using g e t1 o k response
func (o *GetAPIPlanAPIUsingGET1OK) Code() int {
	return 200
}

func (o *GetAPIPlanAPIUsingGET1OK) Error() string {
	return fmt.Sprintf("[GET /api-management/0.1/api-plans/{plan-uuid}/api/{api-uuid}][%d] getApiPlanApiUsingGET1OK  %+v", 200, o.Payload)
}

func (o *GetAPIPlanAPIUsingGET1OK) String() string {
	return fmt.Sprintf("[GET /api-management/0.1/api-plans/{plan-uuid}/api/{api-uuid}][%d] getApiPlanApiUsingGET1OK  %+v", 200, o.Payload)
}

func (o *GetAPIPlanAPIUsingGET1OK) GetPayload() int64 {
	return o.Payload
}

func (o *GetAPIPlanAPIUsingGET1OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIPlanAPIUsingGET1NotFound creates a GetAPIPlanAPIUsingGET1NotFound with default headers values
func NewGetAPIPlanAPIUsingGET1NotFound() *GetAPIPlanAPIUsingGET1NotFound {
	return &GetAPIPlanAPIUsingGET1NotFound{}
}

/*
GetAPIPlanAPIUsingGET1NotFound describes a response with status code 404, with default header values.

Entity not found
*/
type GetAPIPlanAPIUsingGET1NotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this get Api plan Api using g e t1 not found response has a 2xx status code
func (o *GetAPIPlanAPIUsingGET1NotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api plan Api using g e t1 not found response has a 3xx status code
func (o *GetAPIPlanAPIUsingGET1NotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api plan Api using g e t1 not found response has a 4xx status code
func (o *GetAPIPlanAPIUsingGET1NotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api plan Api using g e t1 not found response has a 5xx status code
func (o *GetAPIPlanAPIUsingGET1NotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api plan Api using g e t1 not found response a status code equal to that given
func (o *GetAPIPlanAPIUsingGET1NotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get Api plan Api using g e t1 not found response
func (o *GetAPIPlanAPIUsingGET1NotFound) Code() int {
	return 404
}

func (o *GetAPIPlanAPIUsingGET1NotFound) Error() string {
	return fmt.Sprintf("[GET /api-management/0.1/api-plans/{plan-uuid}/api/{api-uuid}][%d] getApiPlanApiUsingGET1NotFound  %+v", 404, o.Payload)
}

func (o *GetAPIPlanAPIUsingGET1NotFound) String() string {
	return fmt.Sprintf("[GET /api-management/0.1/api-plans/{plan-uuid}/api/{api-uuid}][%d] getApiPlanApiUsingGET1NotFound  %+v", 404, o.Payload)
}

func (o *GetAPIPlanAPIUsingGET1NotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetAPIPlanAPIUsingGET1NotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIPlanAPIUsingGET1InternalServerError creates a GetAPIPlanAPIUsingGET1InternalServerError with default headers values
func NewGetAPIPlanAPIUsingGET1InternalServerError() *GetAPIPlanAPIUsingGET1InternalServerError {
	return &GetAPIPlanAPIUsingGET1InternalServerError{}
}

/*
GetAPIPlanAPIUsingGET1InternalServerError describes a response with status code 500, with default header values.

Internal Server Error. Certain fields are missing from the request.
*/
type GetAPIPlanAPIUsingGET1InternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this get Api plan Api using g e t1 internal server error response has a 2xx status code
func (o *GetAPIPlanAPIUsingGET1InternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api plan Api using g e t1 internal server error response has a 3xx status code
func (o *GetAPIPlanAPIUsingGET1InternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api plan Api using g e t1 internal server error response has a 4xx status code
func (o *GetAPIPlanAPIUsingGET1InternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api plan Api using g e t1 internal server error response has a 5xx status code
func (o *GetAPIPlanAPIUsingGET1InternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api plan Api using g e t1 internal server error response a status code equal to that given
func (o *GetAPIPlanAPIUsingGET1InternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api plan Api using g e t1 internal server error response
func (o *GetAPIPlanAPIUsingGET1InternalServerError) Code() int {
	return 500
}

func (o *GetAPIPlanAPIUsingGET1InternalServerError) Error() string {
	return fmt.Sprintf("[GET /api-management/0.1/api-plans/{plan-uuid}/api/{api-uuid}][%d] getApiPlanApiUsingGET1InternalServerError  %+v", 500, o.Payload)
}

func (o *GetAPIPlanAPIUsingGET1InternalServerError) String() string {
	return fmt.Sprintf("[GET /api-management/0.1/api-plans/{plan-uuid}/api/{api-uuid}][%d] getApiPlanApiUsingGET1InternalServerError  %+v", 500, o.Payload)
}

func (o *GetAPIPlanAPIUsingGET1InternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetAPIPlanAPIUsingGET1InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
