// Code generated by go-swagger; DO NOT EDIT.

package deprecated

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/tsrob/l7portal-go/models"
)

// NewCreateAccountPlanParams creates a new CreateAccountPlanParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateAccountPlanParams() *CreateAccountPlanParams {
	return &CreateAccountPlanParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateAccountPlanParamsWithTimeout creates a new CreateAccountPlanParams object
// with the ability to set a timeout on a request.
func NewCreateAccountPlanParamsWithTimeout(timeout time.Duration) *CreateAccountPlanParams {
	return &CreateAccountPlanParams{
		timeout: timeout,
	}
}

// NewCreateAccountPlanParamsWithContext creates a new CreateAccountPlanParams object
// with the ability to set a context for a request.
func NewCreateAccountPlanParamsWithContext(ctx context.Context) *CreateAccountPlanParams {
	return &CreateAccountPlanParams{
		Context: ctx,
	}
}

// NewCreateAccountPlanParamsWithHTTPClient creates a new CreateAccountPlanParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateAccountPlanParamsWithHTTPClient(client *http.Client) *CreateAccountPlanParams {
	return &CreateAccountPlanParams{
		HTTPClient: client,
	}
}

/*
CreateAccountPlanParams contains all the parameters to send to the API endpoint

	for the create account plan operation.

	Typically these are written to a http.Request.
*/
type CreateAccountPlanParams struct {

	/* Body.

	   Creates an Account Plan.
	*/
	Body *models.AccountPlanPost

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create account plan params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateAccountPlanParams) WithDefaults() *CreateAccountPlanParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create account plan params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateAccountPlanParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create account plan params
func (o *CreateAccountPlanParams) WithTimeout(timeout time.Duration) *CreateAccountPlanParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create account plan params
func (o *CreateAccountPlanParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create account plan params
func (o *CreateAccountPlanParams) WithContext(ctx context.Context) *CreateAccountPlanParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create account plan params
func (o *CreateAccountPlanParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create account plan params
func (o *CreateAccountPlanParams) WithHTTPClient(client *http.Client) *CreateAccountPlanParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create account plan params
func (o *CreateAccountPlanParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create account plan params
func (o *CreateAccountPlanParams) WithBody(body *models.AccountPlanPost) *CreateAccountPlanParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create account plan params
func (o *CreateAccountPlanParams) SetBody(body *models.AccountPlanPost) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateAccountPlanParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
