// Code generated by go-swagger; DO NOT EDIT.

package requests

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewReviewApplicationRequestDetailParams creates a new ReviewApplicationRequestDetailParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewReviewApplicationRequestDetailParams() *ReviewApplicationRequestDetailParams {
	return &ReviewApplicationRequestDetailParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewReviewApplicationRequestDetailParamsWithTimeout creates a new ReviewApplicationRequestDetailParams object
// with the ability to set a timeout on a request.
func NewReviewApplicationRequestDetailParamsWithTimeout(timeout time.Duration) *ReviewApplicationRequestDetailParams {
	return &ReviewApplicationRequestDetailParams{
		timeout: timeout,
	}
}

// NewReviewApplicationRequestDetailParamsWithContext creates a new ReviewApplicationRequestDetailParams object
// with the ability to set a context for a request.
func NewReviewApplicationRequestDetailParamsWithContext(ctx context.Context) *ReviewApplicationRequestDetailParams {
	return &ReviewApplicationRequestDetailParams{
		Context: ctx,
	}
}

// NewReviewApplicationRequestDetailParamsWithHTTPClient creates a new ReviewApplicationRequestDetailParams object
// with the ability to set a custom HTTPClient for a request.
func NewReviewApplicationRequestDetailParamsWithHTTPClient(client *http.Client) *ReviewApplicationRequestDetailParams {
	return &ReviewApplicationRequestDetailParams{
		HTTPClient: client,
	}
}

/*
ReviewApplicationRequestDetailParams contains all the parameters to send to the API endpoint

	for the review application request detail operation.

	Typically these are written to a http.Request.
*/
type ReviewApplicationRequestDetailParams struct {

	/* UUID.

	   The UUID of the request to return.
	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the review application request detail params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReviewApplicationRequestDetailParams) WithDefaults() *ReviewApplicationRequestDetailParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the review application request detail params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReviewApplicationRequestDetailParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the review application request detail params
func (o *ReviewApplicationRequestDetailParams) WithTimeout(timeout time.Duration) *ReviewApplicationRequestDetailParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the review application request detail params
func (o *ReviewApplicationRequestDetailParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the review application request detail params
func (o *ReviewApplicationRequestDetailParams) WithContext(ctx context.Context) *ReviewApplicationRequestDetailParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the review application request detail params
func (o *ReviewApplicationRequestDetailParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the review application request detail params
func (o *ReviewApplicationRequestDetailParams) WithHTTPClient(client *http.Client) *ReviewApplicationRequestDetailParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the review application request detail params
func (o *ReviewApplicationRequestDetailParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUUID adds the uuid to the review application request detail params
func (o *ReviewApplicationRequestDetailParams) WithUUID(uuid string) *ReviewApplicationRequestDetailParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the review application request detail params
func (o *ReviewApplicationRequestDetailParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *ReviewApplicationRequestDetailParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
