// Code generated by go-swagger; DO NOT EDIT.

package tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetOrgTagsParams creates a new GetOrgTagsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetOrgTagsParams() *GetOrgTagsParams {
	return &GetOrgTagsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrgTagsParamsWithTimeout creates a new GetOrgTagsParams object
// with the ability to set a timeout on a request.
func NewGetOrgTagsParamsWithTimeout(timeout time.Duration) *GetOrgTagsParams {
	return &GetOrgTagsParams{
		timeout: timeout,
	}
}

// NewGetOrgTagsParamsWithContext creates a new GetOrgTagsParams object
// with the ability to set a context for a request.
func NewGetOrgTagsParamsWithContext(ctx context.Context) *GetOrgTagsParams {
	return &GetOrgTagsParams{
		Context: ctx,
	}
}

// NewGetOrgTagsParamsWithHTTPClient creates a new GetOrgTagsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetOrgTagsParamsWithHTTPClient(client *http.Client) *GetOrgTagsParams {
	return &GetOrgTagsParams{
		HTTPClient: client,
	}
}

/*
GetOrgTagsParams contains all the parameters to send to the API endpoint

	for the get org tags operation.

	Typically these are written to a http.Request.
*/
type GetOrgTagsParams struct {

	/* InUse.

	   false to filter the list of Tags that are not associated with an ORGANIZATION, true to filter the tags that are already associated with an ORGANIZATION
	*/
	InUse *string

	/* Name.

	   The tagName to filter the list of Tags that can be associated with an Organization.
	*/
	Name *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get org tags params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrgTagsParams) WithDefaults() *GetOrgTagsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get org tags params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrgTagsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get org tags params
func (o *GetOrgTagsParams) WithTimeout(timeout time.Duration) *GetOrgTagsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get org tags params
func (o *GetOrgTagsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get org tags params
func (o *GetOrgTagsParams) WithContext(ctx context.Context) *GetOrgTagsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get org tags params
func (o *GetOrgTagsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get org tags params
func (o *GetOrgTagsParams) WithHTTPClient(client *http.Client) *GetOrgTagsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get org tags params
func (o *GetOrgTagsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInUse adds the inUse to the get org tags params
func (o *GetOrgTagsParams) WithInUse(inUse *string) *GetOrgTagsParams {
	o.SetInUse(inUse)
	return o
}

// SetInUse adds the inUse to the get org tags params
func (o *GetOrgTagsParams) SetInUse(inUse *string) {
	o.InUse = inUse
}

// WithName adds the name to the get org tags params
func (o *GetOrgTagsParams) WithName(name *string) *GetOrgTagsParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get org tags params
func (o *GetOrgTagsParams) SetName(name *string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrgTagsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.InUse != nil {

		// query param inUse
		var qrInUse string

		if o.InUse != nil {
			qrInUse = *o.InUse
		}
		qInUse := qrInUse
		if qInUse != "" {

			if err := r.SetQueryParam("inUse", qInUse); err != nil {
				return err
			}
		}
	}

	if o.Name != nil {

		// query param name
		var qrName string

		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {

			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
