// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// APIEulaBasic Api eula basic
//
// swagger:model ApiEulaBasic
type APIEulaBasic struct {

	// The HTML content of the End-User Licence Agreement. This contains the text that an end-user must agree to in order to access any API that has this EULA applied to it.
	// Required: true
	Content *string `json:"Content"`

	// Name of End-User Licence Agreement which must be unique.
	// Required: true
	// Max Length: 50
	Name *string `json:"Name"`

	// Unique key for this entity which conforms to the UUID standard according to RFC 4122.
	// Required: true
	UUID *string `json:"Uuid"`
}

// Validate validates this Api eula basic
func (m *APIEulaBasic) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateContent(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUUID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIEulaBasic) validateContent(formats strfmt.Registry) error {

	if err := validate.Required("Content", "body", m.Content); err != nil {
		return err
	}

	return nil
}

func (m *APIEulaBasic) validateName(formats strfmt.Registry) error {

	if err := validate.Required("Name", "body", m.Name); err != nil {
		return err
	}

	if err := validate.MaxLength("Name", "body", *m.Name, 50); err != nil {
		return err
	}

	return nil
}

func (m *APIEulaBasic) validateUUID(formats strfmt.Registry) error {

	if err := validate.Required("Uuid", "body", m.UUID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this Api eula basic based on context it is used
func (m *APIEulaBasic) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIEulaBasic) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIEulaBasic) UnmarshalBinary(b []byte) error {
	var res APIEulaBasic
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
