// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DocumentServicePutDocs document service put docs
//
// swagger:model DocumentServicePutDocs
type DocumentServicePutDocs struct {
}

// Validate validates this document service put docs
func (m *DocumentServicePutDocs) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validate this document service put docs based on the context it is used
func (m *DocumentServicePutDocs) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *DocumentServicePutDocs) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DocumentServicePutDocs) UnmarshalBinary(b []byte) error {
	var res DocumentServicePutDocs
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
