// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ErrorEntity error entity
//
// swagger:model ErrorEntity
type ErrorEntity struct {
	ErrorBody

	// detail
	Detail *ErrorDetail `json:"detail,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ErrorEntity) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 ErrorBody
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.ErrorBody = aO0

	// AO1
	var dataAO1 struct {
		Detail *ErrorDetail `json:"detail,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.Detail = dataAO1.Detail

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ErrorEntity) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.ErrorBody)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	var dataAO1 struct {
		Detail *ErrorDetail `json:"detail,omitempty"`
	}

	dataAO1.Detail = m.Detail

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this error entity
func (m *ErrorEntity) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with ErrorBody
	if err := m.ErrorBody.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDetail(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ErrorEntity) validateDetail(formats strfmt.Registry) error {

	if swag.IsZero(m.Detail) { // not required
		return nil
	}

	if m.Detail != nil {
		if err := m.Detail.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("detail")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("detail")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this error entity based on the context it is used
func (m *ErrorEntity) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with ErrorBody
	if err := m.ErrorBody.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDetail(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ErrorEntity) contextValidateDetail(ctx context.Context, formats strfmt.Registry) error {

	if m.Detail != nil {
		if err := m.Detail.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("detail")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("detail")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ErrorEntity) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ErrorEntity) UnmarshalBinary(b []byte) error {
	var res ErrorEntity
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
