// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GatewayBundleAPIBasic gateway bundle Api basic
//
// swagger:model GatewayBundleApiBasic
type GatewayBundleAPIBasic struct {

	// api modify ts
	APIModifyTs int64 `json:"apiModifyTs,omitempty"`

	// api name
	APIName string `json:"apiName,omitempty"`

	// api portal status
	APIPortalStatus string `json:"apiPortalStatus,omitempty"`

	// api proxies
	APIProxies string `json:"apiProxies,omitempty"`

	// api proxy uuids
	APIProxyUuids []string `json:"apiProxyUuids"`

	// api tags
	APITags []string `json:"apiTags"`

	// api version
	APIVersion string `json:"apiVersion,omitempty"`

	// gateway bundle Uuid
	GatewayBundleUUID string `json:"gatewayBundleUuid,omitempty"`

	// uuid
	UUID string `json:"uuid,omitempty"`
}

// Validate validates this gateway bundle Api basic
func (m *GatewayBundleAPIBasic) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this gateway bundle Api basic based on context it is used
func (m *GatewayBundleAPIBasic) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GatewayBundleAPIBasic) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GatewayBundleAPIBasic) UnmarshalBinary(b []byte) error {
	var res GatewayBundleAPIBasic
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
