// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OrgAPIRateQuotasResponse An array of API and Rate Quota(Api Per Org)
// Example: [{"apiUuid":"3571c9b0-a4f6-4908-8a86-3e667c45ffc4","rateQuotaUuid":"77eabfd1-c938-4188-9b7e-a1c5e856a54f"},{"apiUuid":"0a927763-4e95-43d7-9685-2b28f3a9742d","rateQuotaUuid":"df2fc5f6-00cb-4a8d-87f4-33ced2585bfc"}]
//
// swagger:model OrgApiRateQuotasResponse
type OrgAPIRateQuotasResponse []*OrgAPIRateQuotaResponse

// Validate validates this org Api rate quotas response
func (m OrgAPIRateQuotasResponse) Validate(formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(m); i++ {
		if swag.IsZero(m[i]) { // not required
			continue
		}

		if m[i] != nil {
			if err := m[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName(strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName(strconv.Itoa(i))
				}
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this org Api rate quotas response based on the context it is used
func (m OrgAPIRateQuotasResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(m); i++ {

		if m[i] != nil {
			if err := m[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName(strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName(strconv.Itoa(i))
				}
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
