// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ProxyDeployUpdateDto proxy deploy update dto
//
// swagger:model ProxyDeployUpdateDto
type ProxyDeployUpdateDto struct {

	// The deployment type for the proxy.
	// Required: true
	// Enum: [AUTOMATIC ON_DEMAND MANUAL]
	DeploymentType *string `json:"deploymentType"`

	// The name of the proxy.
	// Required: true
	Name *string `json:"name"`
}

// Validate validates this proxy deploy update dto
func (m *ProxyDeployUpdateDto) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDeploymentType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var proxyDeployUpdateDtoTypeDeploymentTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["AUTOMATIC","ON_DEMAND","MANUAL"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		proxyDeployUpdateDtoTypeDeploymentTypePropEnum = append(proxyDeployUpdateDtoTypeDeploymentTypePropEnum, v)
	}
}

const (

	// ProxyDeployUpdateDtoDeploymentTypeAUTOMATIC captures enum value "AUTOMATIC"
	ProxyDeployUpdateDtoDeploymentTypeAUTOMATIC string = "AUTOMATIC"

	// ProxyDeployUpdateDtoDeploymentTypeONDEMAND captures enum value "ON_DEMAND"
	ProxyDeployUpdateDtoDeploymentTypeONDEMAND string = "ON_DEMAND"

	// ProxyDeployUpdateDtoDeploymentTypeMANUAL captures enum value "MANUAL"
	ProxyDeployUpdateDtoDeploymentTypeMANUAL string = "MANUAL"
)

// prop value enum
func (m *ProxyDeployUpdateDto) validateDeploymentTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, proxyDeployUpdateDtoTypeDeploymentTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *ProxyDeployUpdateDto) validateDeploymentType(formats strfmt.Registry) error {

	if err := validate.Required("deploymentType", "body", m.DeploymentType); err != nil {
		return err
	}

	// value enum
	if err := m.validateDeploymentTypeEnum("deploymentType", "body", *m.DeploymentType); err != nil {
		return err
	}

	return nil
}

func (m *ProxyDeployUpdateDto) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this proxy deploy update dto based on context it is used
func (m *ProxyDeployUpdateDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProxyDeployUpdateDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProxyDeployUpdateDto) UnmarshalBinary(b []byte) error {
	var res ProxyDeployUpdateDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
