// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserRoleMappingLink A HateoasLink consists of a link title and an href. The link title describes what the href link refers to - for example - a link_title of 'self' will include an href to a link that can be used to reference the requested object, essentially it is a requested object's reference to itself
//
// swagger:model UserRoleMappingLink
type UserRoleMappingLink struct {

	// self
	Self *UserRoleMappingLinkSelf `json:"self,omitempty"`

	// user
	User *UserRoleMappingLinkUser `json:"user,omitempty"`
}

// Validate validates this user role mapping link
func (m *UserRoleMappingLink) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSelf(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUser(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserRoleMappingLink) validateSelf(formats strfmt.Registry) error {
	if swag.IsZero(m.Self) { // not required
		return nil
	}

	if m.Self != nil {
		if err := m.Self.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("self")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("self")
			}
			return err
		}
	}

	return nil
}

func (m *UserRoleMappingLink) validateUser(formats strfmt.Registry) error {
	if swag.IsZero(m.User) { // not required
		return nil
	}

	if m.User != nil {
		if err := m.User.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("user")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("user")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this user role mapping link based on the context it is used
func (m *UserRoleMappingLink) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSelf(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUser(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserRoleMappingLink) contextValidateSelf(ctx context.Context, formats strfmt.Registry) error {

	if m.Self != nil {
		if err := m.Self.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("self")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("self")
			}
			return err
		}
	}

	return nil
}

func (m *UserRoleMappingLink) contextValidateUser(ctx context.Context, formats strfmt.Registry) error {

	if m.User != nil {
		if err := m.User.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("user")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("user")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UserRoleMappingLink) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserRoleMappingLink) UnmarshalBinary(b []byte) error {
	var res UserRoleMappingLink
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// UserRoleMappingLinkSelf user role mapping link self
//
// swagger:model UserRoleMappingLinkSelf
type UserRoleMappingLinkSelf struct {

	// The link that can be used to fetch the current role mapping details
	Href string `json:"href,omitempty"`
}

// Validate validates this user role mapping link self
func (m *UserRoleMappingLinkSelf) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this user role mapping link self based on context it is used
func (m *UserRoleMappingLinkSelf) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserRoleMappingLinkSelf) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserRoleMappingLinkSelf) UnmarshalBinary(b []byte) error {
	var res UserRoleMappingLinkSelf
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// UserRoleMappingLinkUser user role mapping link user
//
// swagger:model UserRoleMappingLinkUser
type UserRoleMappingLinkUser struct {

	// The link that can be used to access the user details associated with the role mapping
	Href string `json:"href,omitempty"`
}

// Validate validates this user role mapping link user
func (m *UserRoleMappingLinkUser) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this user role mapping link user based on context it is used
func (m *UserRoleMappingLinkUser) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserRoleMappingLinkUser) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserRoleMappingLinkUser) UnmarshalBinary(b []byte) error {
	var res UserRoleMappingLinkUser
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
